; ProbeMonkey ESP32 Firmware
; PlatformIO Configuration

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer
    bblanchon/ArduinoJson@^7
build_flags =
    -D CONFIG_ASYNC_TCP_RUNNING_CORE=0
board_build.filesystem = littlefs
